from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from viewsets import *
from . import views
from forms import *

from rest_framework import routers
# this is DRF router for REST API viewsets
router = routers.DefaultRouter()

# register REST API endpoints with DRF router
router.register(r'player', PlayerViewSet, r"player")


urlpatterns = [

    # REST API root view (generated by DRF router)
    url(r'^api/', include(router.urls, namespace='api')),
    url(r'^signature-form/$',
        #login_required(views.SignatureFormView.as_view()),
        views.SignatureFormView.as_view(),
        name='signature_form'),
    url(r'^$', views.index, name='index'),
]
